language: python
python:
  - "3.7"

before_install:
  - ./install.sh

script:
  - ./make_gtfs.sh
  - ls

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_DEPLOY_TOKEN
  local_dir: output
  keep-history: true
  on:
    branch: master
