name: Make GTFS

on:
  schedule:
    - cron:  '0 0 20 * *'
  push:
    branches-ignore:
      - 'gh-pages'

      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Setup python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: ./install.sh
    - name: Generate GTFS
      run: ./make_gtfs.sh
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output
